site_name: Apollo Documentation
site_url: https://docs.apollo.fyi
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.ico
  features:
    - navigation.sections
  palette:
    - scheme: default
      primary: light blue
      accent: yellow
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: light blue
      accent: yellow
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: True
nav:
  - Home: 'index.md'
  - FAQ: 'faq.md'
  - Commands: 'commands.md'
  - Guides:
    - Creating events: 'creating_events.md'
    - Deleting events: 'deleting_events.md'
    - Modifying events: 'modifying_events.md'
    - Event channels: 'event_channels.md'
